MA-19233-5 Fix 8mm board compilation error caused by 'enable g2d secure pipeline'
Since no macro is used to isolate the unused variables of 8mm, the
following compilation errors will be caused.
> "error: unused variable 'current_g2d_secure_mode'"

Change-Id: Ife31228d1557ba181de115d17e2479d0d8b10389
Signed-off-by: zhai.he <zhai.he@nxp.com>